import { useMemo, useState } from "react";
import { createFileRoute } from "@tanstack/react-router";
import { toast } from "sonner";
import { Server, Gauge, Timer, Ban, Copy, Cpu, KeyRound, Shield } from "lucide-react";
import { MasterShell } from "@/components/master/MasterShell";
import { MSectionHeader, MStat, MTag, MButton, MTable, MTh, MTd, MTr, MField, M_INPUT } from "@/components/master/MasterKit";
import { CUSTOMERS, NAS_NODES } from "@/lib/masterData";

export const Route = createFileRoute("/master/nas")({
  component: NasScreen,
});

// Deterministic pseudo-values so a given (tenant, code, ip) always yields the
// same NAS identity -- no Math.random (keeps generated config reproducible).
function hash(s: string): number {
  let h = 2166136261;
  for (let i = 0; i < s.length; i++) { h ^= s.charCodeAt(i); h = Math.imul(h, 16777619); }
  return h >>> 0;
}
function secret(seed: string): string {
  const chars = "ABCDEFGHJKLMNPQRSTUVWXYZ23456789abcdefghijkmnpqrstuvwxyz";
  let h = hash(seed), out = "";
  for (let i = 0; i < 24; i++) { h = Math.imul(h ^ (i + 7), 16777619) >>> 0; out += chars[h % chars.length]; }
  return out;
}
function wgIp(seed: string): string {
  const h = hash(seed);
  return `10.88.${((h >>> 8) % 254) + 1}.${(h % 254) + 1}/32`;
}

function NasScreen() {
  const [tenant, setTenant] = useState(CUSTOMERS[0].name);
  const [code, setCode] = useState("HT001");
  const [ip, setIp] = useState("103.21.44.2");
  const [mac, setMac] = useState("48:8F:5A:2C:19:D0");

  const gen = useMemo(() => {
    const seed = `${tenant}|${code}|${ip}|${mac}`;
    const nasId = `NAS-${code}-${(hash(seed) % 9000 + 1000)}`;
    return { nasId, sharedSecret: secret(seed), wg: wgIp(seed) };
  }, [tenant, code, ip, mac]);

  const routerOsConfig = `# ${gen.nasId} — generated by ZIP WiFi Master Console
# RADIUS client
/radius add address=radius.cloudguest.io secret=${gen.sharedSecret} service=hotspot,login comment="${tenant} ${code}"
# MAC authorization binding
/interface wireless access-list add mac-address=${mac} interface=all comment="bind ${code}"
# WireGuard management tunnel
/interface wireguard add name=cg-mgmt listen-port=13231
/interface wireguard peers add interface=cg-mgmt public-key="<cloudguest-pub>" endpoint-address=wg.cloudguest.io endpoint-port=51820 allowed-address=10.88.0.0/16
/ip address add address=${gen.wg} interface=cg-mgmt
# Hotspot profile + walled garden
/ip hotspot profile set default use-radius=yes
/ip hotspot walled-garden add dst-host=*.cloudguest.io action=allow`;

  const copy = (text: string, what: string) => {
    navigator.clipboard?.writeText(text).then(() => toast.success(`${what} copied`), () => toast.error("Copy failed"));
  };

  return (
    <MasterShell title="NAS / RADIUS">
      <MSectionHeader eyebrow="Infrastructure" title="NAS / RADIUS" />

      <div className="grid grid-cols-2 gap-3 md:grid-cols-4">
        <MStat label="Auth / sec" value="733" delta="nominal" icon={Gauge} />
        <MStat label="Avg latency" value="14 ms" delta="p95 21 ms" icon={Timer} />
        <MStat label="NAS clients" value="196" delta="182 online" icon={Server} />
        <MStat label="Reject rate" value="0.8%" delta="within SLA" icon={Ban} />
      </div>

      <div className="grid gap-3 lg:grid-cols-2">
        {/* Generator inputs */}
        <div className="rounded-xl border border-border bg-card p-5 shadow-sm">
          <p className="mb-4 flex items-center gap-2 border-b border-border pb-2 text-sm font-semibold">
            <Cpu className="h-4 w-4 text-primary" /> NAS ID Generator
          </p>
          <div className="space-y-3">
            <MField label="Tenant">
              <select className={M_INPUT} value={tenant} onChange={(e) => setTenant(e.target.value)}>
                {CUSTOMERS.map((c) => <option key={c.id}>{c.name}</option>)}
              </select>
            </MField>
            <div className="grid grid-cols-2 gap-3">
              <MField label="Site code"><input className={M_INPUT} value={code} onChange={(e) => setCode(e.target.value.toUpperCase())} placeholder="HT001" /></MField>
              <MField label="Public IP"><input className={M_INPUT} value={ip} onChange={(e) => setIp(e.target.value)} /></MField>
            </div>
            <MField label="Router MAC (bind)"><input className={`${M_INPUT} font-mono`} value={mac} onChange={(e) => setMac(e.target.value.toUpperCase())} /></MField>
            <p className="text-xs text-muted-foreground">Operator-only. Never expose low-level MikroTik config to customers.</p>
          </div>
        </div>

        {/* Generated identity */}
        <div className="rounded-xl border border-primary/40 bg-card p-5 shadow-sm ring-1 ring-primary/10">
          <p className="mb-4 flex items-center gap-2 border-b border-border pb-2 text-sm font-semibold">
            <KeyRound className="h-4 w-4 text-primary" /> Generated Identity
          </p>
          <dl className="space-y-3 text-sm">
            {[
              { k: "NAS ID", v: gen.nasId },
              { k: "Shared secret", v: gen.sharedSecret, mono: true },
              { k: "Bound MAC", v: mac, mono: true },
              { k: "WireGuard mgmt IP", v: gen.wg, mono: true },
            ].map((r) => (
              <div key={r.k} className="flex items-center justify-between gap-3 border-b border-border/70 pb-2">
                <dt className="text-xs font-medium text-muted-foreground">{r.k}</dt>
                <dd className="flex items-center gap-2">
                  <span className={r.mono ? "font-mono text-xs" : "font-semibold"}>{r.v}</span>
                  <button onClick={() => copy(r.v, r.k)} className="text-muted-foreground hover:text-primary"><Copy className="h-3.5 w-3.5" /></button>
                </dd>
              </div>
            ))}
          </dl>
        </div>
      </div>

      {/* RouterOS config */}
      <div className="overflow-hidden rounded-xl border border-border bg-card shadow-sm">
        <div className="flex items-center justify-between border-b border-border p-4">
          <p className="flex items-center gap-2 text-sm font-semibold"><Shield className="h-4 w-4 text-primary" /> MikroTik RouterOS Config</p>
          <MButton variant="outline" onClick={() => copy(routerOsConfig, "RouterOS config")}><Copy /> Copy</MButton>
        </div>
        <pre className="overflow-x-auto bg-[oklch(0.16_0.004_50)] p-4 font-mono text-[11px] leading-relaxed text-emerald-300/90">{routerOsConfig}</pre>
      </div>

      {/* Cluster nodes */}
      <div>
        <p className="mb-2 text-sm font-semibold">RADIUS Cluster Nodes</p>
        <MTable head={<><MTh>Host</MTh><MTh>Region</MTh><MTh>Auth/s</MTh><MTh>Latency</MTh><MTh>Status</MTh></>}>
          {NAS_NODES.map((n) => (
            <MTr key={n.id}>
              <MTd className="font-mono text-sm font-bold">{n.host}</MTd>
              <MTd>{n.region}</MTd>
              <MTd className="tabular-nums">{n.authPerSec}</MTd>
              <MTd className="tabular-nums">{n.latencyMs} ms</MTd>
              <MTd><MTag label={n.status} /></MTd>
            </MTr>
          ))}
        </MTable>
      </div>
    </MasterShell>
  );
}
