/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedRoutersIndexRouteImport } from './routes/_authenticated/routers.index'
import { Route as AuthenticatedPortalsIndexRouteImport } from './routes/_authenticated/portals.index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring.index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedGuestsIndexRouteImport } from './routes/_authenticated/guests.index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as AuthenticatedRoutersRouterIdRouteImport } from './routes/_authenticated/routers.$routerId'
import { Route as AuthenticatedPortalsPortalIdRouteImport } from './routes/_authenticated/portals.$portalId'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated/organizations.$orgId'
import { Route as AuthenticatedLocationsLocationIdRouteImport } from './routes/_authenticated/locations.$locationId'
import { Route as AuthenticatedGuestsGuestIdRouteImport } from './routes/_authenticated/guests.$guestId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedRoutersIndexRoute =
  AuthenticatedRoutersIndexRouteImport.update({
    id: '/routers/',
    path: '/routers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalsIndexRoute =
  AuthenticatedPortalsIndexRouteImport.update({
    id: '/portals/',
    path: '/portals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuestsIndexRoute =
  AuthenticatedGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutersRouterIdRoute =
  AuthenticatedRoutersRouterIdRouteImport.update({
    id: '/routers/$routerId',
    path: '/routers/$routerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalsPortalIdRoute =
  AuthenticatedPortalsPortalIdRouteImport.update({
    id: '/portals/$portalId',
    path: '/portals/$portalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsLocationIdRoute =
  AuthenticatedLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuestsGuestIdRoute =
  AuthenticatedGuestsGuestIdRouteImport.update({
    id: '/guests/$guestId',
    path: '/guests/$guestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/guests/': typeof AuthenticatedGuestsIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/portals/': typeof AuthenticatedPortalsIndexRoute
  '/routers/': typeof AuthenticatedRoutersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/guests': typeof AuthenticatedGuestsIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/portals': typeof AuthenticatedPortalsIndexRoute
  '/routers': typeof AuthenticatedRoutersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/_authenticated/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/_authenticated/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/_authenticated/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/guests/': typeof AuthenticatedGuestsIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/portals/': typeof AuthenticatedPortalsIndexRoute
  '/_authenticated/routers/': typeof AuthenticatedRoutersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/dashboard'
    | '/guests/$guestId'
    | '/locations/$locationId'
    | '/organizations/$orgId'
    | '/portals/$portalId'
    | '/routers/$routerId'
    | '/analytics/'
    | '/guests/'
    | '/locations/'
    | '/monitoring/'
    | '/organizations/'
    | '/portals/'
    | '/routers/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/dashboard'
    | '/guests/$guestId'
    | '/locations/$locationId'
    | '/organizations/$orgId'
    | '/portals/$portalId'
    | '/routers/$routerId'
    | '/analytics'
    | '/guests'
    | '/locations'
    | '/monitoring'
    | '/organizations'
    | '/portals'
    | '/routers'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/_authenticated/dashboard'
    | '/_authenticated/guests/$guestId'
    | '/_authenticated/locations/$locationId'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/portals/$portalId'
    | '/_authenticated/routers/$routerId'
    | '/_authenticated/analytics/'
    | '/_authenticated/guests/'
    | '/_authenticated/locations/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/organizations/'
    | '/_authenticated/portals/'
    | '/_authenticated/routers/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routers/': {
      id: '/_authenticated/routers/'
      path: '/routers'
      fullPath: '/routers/'
      preLoaderRoute: typeof AuthenticatedRoutersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portals/': {
      id: '/_authenticated/portals/'
      path: '/portals'
      fullPath: '/portals/'
      preLoaderRoute: typeof AuthenticatedPortalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests/': {
      id: '/_authenticated/guests/'
      path: '/guests'
      fullPath: '/guests/'
      preLoaderRoute: typeof AuthenticatedGuestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routers/$routerId': {
      id: '/_authenticated/routers/$routerId'
      path: '/routers/$routerId'
      fullPath: '/routers/$routerId'
      preLoaderRoute: typeof AuthenticatedRoutersRouterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portals/$portalId': {
      id: '/_authenticated/portals/$portalId'
      path: '/portals/$portalId'
      fullPath: '/portals/$portalId'
      preLoaderRoute: typeof AuthenticatedPortalsPortalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/$locationId': {
      id: '/_authenticated/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests/$guestId': {
      id: '/_authenticated/guests/$guestId'
      path: '/guests/$guestId'
      fullPath: '/guests/$guestId'
      preLoaderRoute: typeof AuthenticatedGuestsGuestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedGuestsGuestIdRoute: typeof AuthenticatedGuestsGuestIdRoute
  AuthenticatedLocationsLocationIdRoute: typeof AuthenticatedLocationsLocationIdRoute
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRoute
  AuthenticatedPortalsPortalIdRoute: typeof AuthenticatedPortalsPortalIdRoute
  AuthenticatedRoutersRouterIdRoute: typeof AuthenticatedRoutersRouterIdRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedGuestsIndexRoute: typeof AuthenticatedGuestsIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPortalsIndexRoute: typeof AuthenticatedPortalsIndexRoute
  AuthenticatedRoutersIndexRoute: typeof AuthenticatedRoutersIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedGuestsGuestIdRoute: AuthenticatedGuestsGuestIdRoute,
  AuthenticatedLocationsLocationIdRoute: AuthenticatedLocationsLocationIdRoute,
  AuthenticatedOrganizationsOrgIdRoute: AuthenticatedOrganizationsOrgIdRoute,
  AuthenticatedPortalsPortalIdRoute: AuthenticatedPortalsPortalIdRoute,
  AuthenticatedRoutersRouterIdRoute: AuthenticatedRoutersRouterIdRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedGuestsIndexRoute: AuthenticatedGuestsIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPortalsIndexRoute: AuthenticatedPortalsIndexRoute,
  AuthenticatedRoutersIndexRoute: AuthenticatedRoutersIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
