/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyOtpRouteImport } from './routes/verify-otp'
import { Route as SessionExpiredRouteImport } from './routes/session-expired'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as PortalRouteImport } from './routes/portal'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PortalIndexRouteImport } from './routes/portal.index'
import { Route as PortalWelcomeRouteImport } from './routes/portal.welcome'
import { Route as PortalVerifyRouteImport } from './routes/portal.verify'
import { Route as PortalTermsRouteImport } from './routes/portal.terms'
import { Route as PortalSuccessRouteImport } from './routes/portal.success'
import { Route as PortalSessionRouteImport } from './routes/portal.session'
import { Route as PortalRedirectRouteImport } from './routes/portal.redirect'
import { Route as PortalOfflineRouteImport } from './routes/portal.offline'
import { Route as PortalFailureRouteImport } from './routes/portal.failure'
import { Route as PortalExpiredRouteImport } from './routes/portal.expired'
import { Route as PortalAuthRouteImport } from './routes/portal.auth'
import { Route as PortalAdRouteImport } from './routes/portal.ad'
import { Route as AuthenticatedWorkspaceRouteImport } from './routes/_authenticated/workspace'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedWorkspaceIndexRouteImport } from './routes/_authenticated/workspace.index'
import { Route as AuthenticatedSystemIndexRouteImport } from './routes/_authenticated/system.index'
import { Route as AuthenticatedSubscriptionIndexRouteImport } from './routes/_authenticated/subscription.index'
import { Route as AuthenticatedSettingsIndexRouteImport } from './routes/_authenticated/settings.index'
import { Route as AuthenticatedRoutersIndexRouteImport } from './routes/_authenticated/routers.index'
import { Route as AuthenticatedRbacIndexRouteImport } from './routes/_authenticated/rbac.index'
import { Route as AuthenticatedPortalsIndexRouteImport } from './routes/_authenticated/portals.index'
import { Route as AuthenticatedPlansIndexRouteImport } from './routes/_authenticated/plans.index'
import { Route as AuthenticatedOrganizationsIndexRouteImport } from './routes/_authenticated/organizations.index'
import { Route as AuthenticatedOnboardingIndexRouteImport } from './routes/_authenticated/onboarding.index'
import { Route as AuthenticatedNotificationsIndexRouteImport } from './routes/_authenticated/notifications.index'
import { Route as AuthenticatedMonitoringIndexRouteImport } from './routes/_authenticated/monitoring.index'
import { Route as AuthenticatedMarketplaceIndexRouteImport } from './routes/_authenticated/marketplace.index'
import { Route as AuthenticatedLocationsIndexRouteImport } from './routes/_authenticated/locations.index'
import { Route as AuthenticatedIntegrationsIndexRouteImport } from './routes/_authenticated/integrations.index'
import { Route as AuthenticatedHelpIndexRouteImport } from './routes/_authenticated/help.index'
import { Route as AuthenticatedGuestsIndexRouteImport } from './routes/_authenticated/guests.index'
import { Route as AuthenticatedFeatureManagementIndexRouteImport } from './routes/_authenticated/feature-management.index'
import { Route as AuthenticatedExportsIndexRouteImport } from './routes/_authenticated/exports.index'
import { Route as AuthenticatedCustomersIndexRouteImport } from './routes/_authenticated/customers.index'
import { Route as AuthenticatedBrandingIndexRouteImport } from './routes/_authenticated/branding.index'
import { Route as AuthenticatedBillingIndexRouteImport } from './routes/_authenticated/billing.index'
import { Route as AuthenticatedAuditIndexRouteImport } from './routes/_authenticated/audit.index'
import { Route as AuthenticatedApiKeysIndexRouteImport } from './routes/_authenticated/api-keys.index'
import { Route as AuthenticatedAnalyticsIndexRouteImport } from './routes/_authenticated/analytics.index'
import { Route as PortalAuthMethodRouteImport } from './routes/portal.auth.$method'
import { Route as AuthenticatedWorkspaceStaffRouteImport } from './routes/_authenticated/workspace.staff'
import { Route as AuthenticatedWorkspaceRoutersRouteImport } from './routes/_authenticated/workspace.routers'
import { Route as AuthenticatedWorkspaceReportsRouteImport } from './routes/_authenticated/workspace.reports'
import { Route as AuthenticatedWorkspaceNotificationsRouteImport } from './routes/_authenticated/workspace.notifications'
import { Route as AuthenticatedWorkspaceLocationsRouteImport } from './routes/_authenticated/workspace.locations'
import { Route as AuthenticatedWorkspaceHelpRouteImport } from './routes/_authenticated/workspace.help'
import { Route as AuthenticatedWorkspaceGuestsRouteImport } from './routes/_authenticated/workspace.guests'
import { Route as AuthenticatedWorkspaceCompanyRouteImport } from './routes/_authenticated/workspace.company'
import { Route as AuthenticatedWorkspaceBillingRouteImport } from './routes/_authenticated/workspace.billing'
import { Route as AuthenticatedWorkspaceAuditRouteImport } from './routes/_authenticated/workspace.audit'
import { Route as AuthenticatedWorkspaceAnalyticsRouteImport } from './routes/_authenticated/workspace.analytics'
import { Route as AuthenticatedRoutersRouterIdRouteImport } from './routes/_authenticated/routers.$routerId'
import { Route as AuthenticatedPortalsPortalIdRouteImport } from './routes/_authenticated/portals.$portalId'
import { Route as AuthenticatedOrganizationsOrgIdRouteImport } from './routes/_authenticated/organizations.$orgId'
import { Route as AuthenticatedLocationsLocationIdRouteImport } from './routes/_authenticated/locations.$locationId'
import { Route as AuthenticatedGuestsGuestIdRouteImport } from './routes/_authenticated/guests.$guestId'
import { Route as AuthenticatedCustomersCustomerIdRouteImport } from './routes/_authenticated/customers.$customerId'
import { Route as AuthenticatedWorkspaceLocationsLocationIdRouteImport } from './routes/_authenticated/workspace.locations.$locationId'

const VerifyOtpRoute = VerifyOtpRouteImport.update({
  id: '/verify-otp',
  path: '/verify-otp',
  getParentRoute: () => rootRouteImport,
} as any)
const SessionExpiredRoute = SessionExpiredRouteImport.update({
  id: '/session-expired',
  path: '/session-expired',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalRoute = PortalRouteImport.update({
  id: '/portal',
  path: '/portal',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalIndexRoute = PortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalRoute,
} as any)
const PortalWelcomeRoute = PortalWelcomeRouteImport.update({
  id: '/welcome',
  path: '/welcome',
  getParentRoute: () => PortalRoute,
} as any)
const PortalVerifyRoute = PortalVerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => PortalRoute,
} as any)
const PortalTermsRoute = PortalTermsRouteImport.update({
  id: '/terms',
  path: '/terms',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSuccessRoute = PortalSuccessRouteImport.update({
  id: '/success',
  path: '/success',
  getParentRoute: () => PortalRoute,
} as any)
const PortalSessionRoute = PortalSessionRouteImport.update({
  id: '/session',
  path: '/session',
  getParentRoute: () => PortalRoute,
} as any)
const PortalRedirectRoute = PortalRedirectRouteImport.update({
  id: '/redirect',
  path: '/redirect',
  getParentRoute: () => PortalRoute,
} as any)
const PortalOfflineRoute = PortalOfflineRouteImport.update({
  id: '/offline',
  path: '/offline',
  getParentRoute: () => PortalRoute,
} as any)
const PortalFailureRoute = PortalFailureRouteImport.update({
  id: '/failure',
  path: '/failure',
  getParentRoute: () => PortalRoute,
} as any)
const PortalExpiredRoute = PortalExpiredRouteImport.update({
  id: '/expired',
  path: '/expired',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAuthRoute = PortalAuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => PortalRoute,
} as any)
const PortalAdRoute = PortalAdRouteImport.update({
  id: '/ad',
  path: '/ad',
  getParentRoute: () => PortalRoute,
} as any)
const AuthenticatedWorkspaceRoute = AuthenticatedWorkspaceRouteImport.update({
  id: '/workspace',
  path: '/workspace',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedWorkspaceIndexRoute =
  AuthenticatedWorkspaceIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedSystemIndexRoute =
  AuthenticatedSystemIndexRouteImport.update({
    id: '/system/',
    path: '/system/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSubscriptionIndexRoute =
  AuthenticatedSubscriptionIndexRouteImport.update({
    id: '/subscription/',
    path: '/subscription/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedSettingsIndexRoute =
  AuthenticatedSettingsIndexRouteImport.update({
    id: '/settings/',
    path: '/settings/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRoutersIndexRoute =
  AuthenticatedRoutersIndexRouteImport.update({
    id: '/routers/',
    path: '/routers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedRbacIndexRoute = AuthenticatedRbacIndexRouteImport.update({
  id: '/rbac/',
  path: '/rbac/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedPortalsIndexRoute =
  AuthenticatedPortalsIndexRouteImport.update({
    id: '/portals/',
    path: '/portals/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPlansIndexRoute = AuthenticatedPlansIndexRouteImport.update({
  id: '/plans/',
  path: '/plans/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedOrganizationsIndexRoute =
  AuthenticatedOrganizationsIndexRouteImport.update({
    id: '/organizations/',
    path: '/organizations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOnboardingIndexRoute =
  AuthenticatedOnboardingIndexRouteImport.update({
    id: '/onboarding/',
    path: '/onboarding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedNotificationsIndexRoute =
  AuthenticatedNotificationsIndexRouteImport.update({
    id: '/notifications/',
    path: '/notifications/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMonitoringIndexRoute =
  AuthenticatedMonitoringIndexRouteImport.update({
    id: '/monitoring/',
    path: '/monitoring/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedMarketplaceIndexRoute =
  AuthenticatedMarketplaceIndexRouteImport.update({
    id: '/marketplace/',
    path: '/marketplace/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsIndexRoute =
  AuthenticatedLocationsIndexRouteImport.update({
    id: '/locations/',
    path: '/locations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedIntegrationsIndexRoute =
  AuthenticatedIntegrationsIndexRouteImport.update({
    id: '/integrations/',
    path: '/integrations/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedHelpIndexRoute = AuthenticatedHelpIndexRouteImport.update({
  id: '/help/',
  path: '/help/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedGuestsIndexRoute =
  AuthenticatedGuestsIndexRouteImport.update({
    id: '/guests/',
    path: '/guests/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedFeatureManagementIndexRoute =
  AuthenticatedFeatureManagementIndexRouteImport.update({
    id: '/feature-management/',
    path: '/feature-management/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedExportsIndexRoute =
  AuthenticatedExportsIndexRouteImport.update({
    id: '/exports/',
    path: '/exports/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersIndexRoute =
  AuthenticatedCustomersIndexRouteImport.update({
    id: '/customers/',
    path: '/customers/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBrandingIndexRoute =
  AuthenticatedBrandingIndexRouteImport.update({
    id: '/branding/',
    path: '/branding/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedBillingIndexRoute =
  AuthenticatedBillingIndexRouteImport.update({
    id: '/billing/',
    path: '/billing/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAuditIndexRoute = AuthenticatedAuditIndexRouteImport.update({
  id: '/audit/',
  path: '/audit/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedApiKeysIndexRoute =
  AuthenticatedApiKeysIndexRouteImport.update({
    id: '/api-keys/',
    path: '/api-keys/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAnalyticsIndexRoute =
  AuthenticatedAnalyticsIndexRouteImport.update({
    id: '/analytics/',
    path: '/analytics/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const PortalAuthMethodRoute = PortalAuthMethodRouteImport.update({
  id: '/$method',
  path: '/$method',
  getParentRoute: () => PortalAuthRoute,
} as any)
const AuthenticatedWorkspaceStaffRoute =
  AuthenticatedWorkspaceStaffRouteImport.update({
    id: '/staff',
    path: '/staff',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceRoutersRoute =
  AuthenticatedWorkspaceRoutersRouteImport.update({
    id: '/routers',
    path: '/routers',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceReportsRoute =
  AuthenticatedWorkspaceReportsRouteImport.update({
    id: '/reports',
    path: '/reports',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceNotificationsRoute =
  AuthenticatedWorkspaceNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceLocationsRoute =
  AuthenticatedWorkspaceLocationsRouteImport.update({
    id: '/locations',
    path: '/locations',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceHelpRoute =
  AuthenticatedWorkspaceHelpRouteImport.update({
    id: '/help',
    path: '/help',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceGuestsRoute =
  AuthenticatedWorkspaceGuestsRouteImport.update({
    id: '/guests',
    path: '/guests',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceCompanyRoute =
  AuthenticatedWorkspaceCompanyRouteImport.update({
    id: '/company',
    path: '/company',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceBillingRoute =
  AuthenticatedWorkspaceBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAuditRoute =
  AuthenticatedWorkspaceAuditRouteImport.update({
    id: '/audit',
    path: '/audit',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedWorkspaceAnalyticsRoute =
  AuthenticatedWorkspaceAnalyticsRouteImport.update({
    id: '/analytics',
    path: '/analytics',
    getParentRoute: () => AuthenticatedWorkspaceRoute,
  } as any)
const AuthenticatedRoutersRouterIdRoute =
  AuthenticatedRoutersRouterIdRouteImport.update({
    id: '/routers/$routerId',
    path: '/routers/$routerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedPortalsPortalIdRoute =
  AuthenticatedPortalsPortalIdRouteImport.update({
    id: '/portals/$portalId',
    path: '/portals/$portalId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedOrganizationsOrgIdRoute =
  AuthenticatedOrganizationsOrgIdRouteImport.update({
    id: '/organizations/$orgId',
    path: '/organizations/$orgId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedLocationsLocationIdRoute =
  AuthenticatedLocationsLocationIdRouteImport.update({
    id: '/locations/$locationId',
    path: '/locations/$locationId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedGuestsGuestIdRoute =
  AuthenticatedGuestsGuestIdRouteImport.update({
    id: '/guests/$guestId',
    path: '/guests/$guestId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedCustomersCustomerIdRoute =
  AuthenticatedCustomersCustomerIdRouteImport.update({
    id: '/customers/$customerId',
    path: '/customers/$customerId',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspaceLocationsLocationIdRoute =
  AuthenticatedWorkspaceLocationsLocationIdRouteImport.update({
    id: '/$locationId',
    path: '/$locationId',
    getParentRoute: () => AuthenticatedWorkspaceLocationsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/portal/ad': typeof PortalAdRoute
  '/portal/auth': typeof PortalAuthRouteWithChildren
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/failure': typeof PortalFailureRoute
  '/portal/offline': typeof PortalOfflineRoute
  '/portal/redirect': typeof PortalRedirectRoute
  '/portal/session': typeof PortalSessionRoute
  '/portal/success': typeof PortalSuccessRoute
  '/portal/terms': typeof PortalTermsRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/portal/': typeof PortalIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/workspace/analytics': typeof AuthenticatedWorkspaceAnalyticsRoute
  '/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/workspace/billing': typeof AuthenticatedWorkspaceBillingRoute
  '/workspace/company': typeof AuthenticatedWorkspaceCompanyRoute
  '/workspace/guests': typeof AuthenticatedWorkspaceGuestsRoute
  '/workspace/help': typeof AuthenticatedWorkspaceHelpRoute
  '/workspace/locations': typeof AuthenticatedWorkspaceLocationsRouteWithChildren
  '/workspace/notifications': typeof AuthenticatedWorkspaceNotificationsRoute
  '/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/workspace/routers': typeof AuthenticatedWorkspaceRoutersRoute
  '/workspace/staff': typeof AuthenticatedWorkspaceStaffRoute
  '/portal/auth/$method': typeof PortalAuthMethodRoute
  '/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/audit/': typeof AuthenticatedAuditIndexRoute
  '/billing/': typeof AuthenticatedBillingIndexRoute
  '/branding/': typeof AuthenticatedBrandingIndexRoute
  '/customers/': typeof AuthenticatedCustomersIndexRoute
  '/exports/': typeof AuthenticatedExportsIndexRoute
  '/feature-management/': typeof AuthenticatedFeatureManagementIndexRoute
  '/guests/': typeof AuthenticatedGuestsIndexRoute
  '/help/': typeof AuthenticatedHelpIndexRoute
  '/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/locations/': typeof AuthenticatedLocationsIndexRoute
  '/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/plans/': typeof AuthenticatedPlansIndexRoute
  '/portals/': typeof AuthenticatedPortalsIndexRoute
  '/rbac/': typeof AuthenticatedRbacIndexRoute
  '/routers/': typeof AuthenticatedRoutersIndexRoute
  '/settings/': typeof AuthenticatedSettingsIndexRoute
  '/subscription/': typeof AuthenticatedSubscriptionIndexRoute
  '/system/': typeof AuthenticatedSystemIndexRoute
  '/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/locations/$locationId': typeof AuthenticatedWorkspaceLocationsLocationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/portal/ad': typeof PortalAdRoute
  '/portal/auth': typeof PortalAuthRouteWithChildren
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/failure': typeof PortalFailureRoute
  '/portal/offline': typeof PortalOfflineRoute
  '/portal/redirect': typeof PortalRedirectRoute
  '/portal/session': typeof PortalSessionRoute
  '/portal/success': typeof PortalSuccessRoute
  '/portal/terms': typeof PortalTermsRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/portal': typeof PortalIndexRoute
  '/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/workspace/analytics': typeof AuthenticatedWorkspaceAnalyticsRoute
  '/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/workspace/billing': typeof AuthenticatedWorkspaceBillingRoute
  '/workspace/company': typeof AuthenticatedWorkspaceCompanyRoute
  '/workspace/guests': typeof AuthenticatedWorkspaceGuestsRoute
  '/workspace/help': typeof AuthenticatedWorkspaceHelpRoute
  '/workspace/locations': typeof AuthenticatedWorkspaceLocationsRouteWithChildren
  '/workspace/notifications': typeof AuthenticatedWorkspaceNotificationsRoute
  '/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/workspace/routers': typeof AuthenticatedWorkspaceRoutersRoute
  '/workspace/staff': typeof AuthenticatedWorkspaceStaffRoute
  '/portal/auth/$method': typeof PortalAuthMethodRoute
  '/analytics': typeof AuthenticatedAnalyticsIndexRoute
  '/api-keys': typeof AuthenticatedApiKeysIndexRoute
  '/audit': typeof AuthenticatedAuditIndexRoute
  '/billing': typeof AuthenticatedBillingIndexRoute
  '/branding': typeof AuthenticatedBrandingIndexRoute
  '/customers': typeof AuthenticatedCustomersIndexRoute
  '/exports': typeof AuthenticatedExportsIndexRoute
  '/feature-management': typeof AuthenticatedFeatureManagementIndexRoute
  '/guests': typeof AuthenticatedGuestsIndexRoute
  '/help': typeof AuthenticatedHelpIndexRoute
  '/integrations': typeof AuthenticatedIntegrationsIndexRoute
  '/locations': typeof AuthenticatedLocationsIndexRoute
  '/marketplace': typeof AuthenticatedMarketplaceIndexRoute
  '/monitoring': typeof AuthenticatedMonitoringIndexRoute
  '/notifications': typeof AuthenticatedNotificationsIndexRoute
  '/onboarding': typeof AuthenticatedOnboardingIndexRoute
  '/organizations': typeof AuthenticatedOrganizationsIndexRoute
  '/plans': typeof AuthenticatedPlansIndexRoute
  '/portals': typeof AuthenticatedPortalsIndexRoute
  '/rbac': typeof AuthenticatedRbacIndexRoute
  '/routers': typeof AuthenticatedRoutersIndexRoute
  '/settings': typeof AuthenticatedSettingsIndexRoute
  '/subscription': typeof AuthenticatedSubscriptionIndexRoute
  '/system': typeof AuthenticatedSystemIndexRoute
  '/workspace': typeof AuthenticatedWorkspaceIndexRoute
  '/workspace/locations/$locationId': typeof AuthenticatedWorkspaceLocationsLocationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/portal': typeof PortalRouteWithChildren
  '/reset-password': typeof ResetPasswordRoute
  '/session-expired': typeof SessionExpiredRoute
  '/verify-otp': typeof VerifyOtpRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/workspace': typeof AuthenticatedWorkspaceRouteWithChildren
  '/portal/ad': typeof PortalAdRoute
  '/portal/auth': typeof PortalAuthRouteWithChildren
  '/portal/expired': typeof PortalExpiredRoute
  '/portal/failure': typeof PortalFailureRoute
  '/portal/offline': typeof PortalOfflineRoute
  '/portal/redirect': typeof PortalRedirectRoute
  '/portal/session': typeof PortalSessionRoute
  '/portal/success': typeof PortalSuccessRoute
  '/portal/terms': typeof PortalTermsRoute
  '/portal/verify': typeof PortalVerifyRoute
  '/portal/welcome': typeof PortalWelcomeRoute
  '/portal/': typeof PortalIndexRoute
  '/_authenticated/customers/$customerId': typeof AuthenticatedCustomersCustomerIdRoute
  '/_authenticated/guests/$guestId': typeof AuthenticatedGuestsGuestIdRoute
  '/_authenticated/locations/$locationId': typeof AuthenticatedLocationsLocationIdRoute
  '/_authenticated/organizations/$orgId': typeof AuthenticatedOrganizationsOrgIdRoute
  '/_authenticated/portals/$portalId': typeof AuthenticatedPortalsPortalIdRoute
  '/_authenticated/routers/$routerId': typeof AuthenticatedRoutersRouterIdRoute
  '/_authenticated/workspace/analytics': typeof AuthenticatedWorkspaceAnalyticsRoute
  '/_authenticated/workspace/audit': typeof AuthenticatedWorkspaceAuditRoute
  '/_authenticated/workspace/billing': typeof AuthenticatedWorkspaceBillingRoute
  '/_authenticated/workspace/company': typeof AuthenticatedWorkspaceCompanyRoute
  '/_authenticated/workspace/guests': typeof AuthenticatedWorkspaceGuestsRoute
  '/_authenticated/workspace/help': typeof AuthenticatedWorkspaceHelpRoute
  '/_authenticated/workspace/locations': typeof AuthenticatedWorkspaceLocationsRouteWithChildren
  '/_authenticated/workspace/notifications': typeof AuthenticatedWorkspaceNotificationsRoute
  '/_authenticated/workspace/reports': typeof AuthenticatedWorkspaceReportsRoute
  '/_authenticated/workspace/routers': typeof AuthenticatedWorkspaceRoutersRoute
  '/_authenticated/workspace/staff': typeof AuthenticatedWorkspaceStaffRoute
  '/portal/auth/$method': typeof PortalAuthMethodRoute
  '/_authenticated/analytics/': typeof AuthenticatedAnalyticsIndexRoute
  '/_authenticated/api-keys/': typeof AuthenticatedApiKeysIndexRoute
  '/_authenticated/audit/': typeof AuthenticatedAuditIndexRoute
  '/_authenticated/billing/': typeof AuthenticatedBillingIndexRoute
  '/_authenticated/branding/': typeof AuthenticatedBrandingIndexRoute
  '/_authenticated/customers/': typeof AuthenticatedCustomersIndexRoute
  '/_authenticated/exports/': typeof AuthenticatedExportsIndexRoute
  '/_authenticated/feature-management/': typeof AuthenticatedFeatureManagementIndexRoute
  '/_authenticated/guests/': typeof AuthenticatedGuestsIndexRoute
  '/_authenticated/help/': typeof AuthenticatedHelpIndexRoute
  '/_authenticated/integrations/': typeof AuthenticatedIntegrationsIndexRoute
  '/_authenticated/locations/': typeof AuthenticatedLocationsIndexRoute
  '/_authenticated/marketplace/': typeof AuthenticatedMarketplaceIndexRoute
  '/_authenticated/monitoring/': typeof AuthenticatedMonitoringIndexRoute
  '/_authenticated/notifications/': typeof AuthenticatedNotificationsIndexRoute
  '/_authenticated/onboarding/': typeof AuthenticatedOnboardingIndexRoute
  '/_authenticated/organizations/': typeof AuthenticatedOrganizationsIndexRoute
  '/_authenticated/plans/': typeof AuthenticatedPlansIndexRoute
  '/_authenticated/portals/': typeof AuthenticatedPortalsIndexRoute
  '/_authenticated/rbac/': typeof AuthenticatedRbacIndexRoute
  '/_authenticated/routers/': typeof AuthenticatedRoutersIndexRoute
  '/_authenticated/settings/': typeof AuthenticatedSettingsIndexRoute
  '/_authenticated/subscription/': typeof AuthenticatedSubscriptionIndexRoute
  '/_authenticated/system/': typeof AuthenticatedSystemIndexRoute
  '/_authenticated/workspace/': typeof AuthenticatedWorkspaceIndexRoute
  '/_authenticated/workspace/locations/$locationId': typeof AuthenticatedWorkspaceLocationsLocationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/dashboard'
    | '/workspace'
    | '/portal/ad'
    | '/portal/auth'
    | '/portal/expired'
    | '/portal/failure'
    | '/portal/offline'
    | '/portal/redirect'
    | '/portal/session'
    | '/portal/success'
    | '/portal/terms'
    | '/portal/verify'
    | '/portal/welcome'
    | '/portal/'
    | '/customers/$customerId'
    | '/guests/$guestId'
    | '/locations/$locationId'
    | '/organizations/$orgId'
    | '/portals/$portalId'
    | '/routers/$routerId'
    | '/workspace/analytics'
    | '/workspace/audit'
    | '/workspace/billing'
    | '/workspace/company'
    | '/workspace/guests'
    | '/workspace/help'
    | '/workspace/locations'
    | '/workspace/notifications'
    | '/workspace/reports'
    | '/workspace/routers'
    | '/workspace/staff'
    | '/portal/auth/$method'
    | '/analytics/'
    | '/api-keys/'
    | '/audit/'
    | '/billing/'
    | '/branding/'
    | '/customers/'
    | '/exports/'
    | '/feature-management/'
    | '/guests/'
    | '/help/'
    | '/integrations/'
    | '/locations/'
    | '/marketplace/'
    | '/monitoring/'
    | '/notifications/'
    | '/onboarding/'
    | '/organizations/'
    | '/plans/'
    | '/portals/'
    | '/rbac/'
    | '/routers/'
    | '/settings/'
    | '/subscription/'
    | '/system/'
    | '/workspace/'
    | '/workspace/locations/$locationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/dashboard'
    | '/portal/ad'
    | '/portal/auth'
    | '/portal/expired'
    | '/portal/failure'
    | '/portal/offline'
    | '/portal/redirect'
    | '/portal/session'
    | '/portal/success'
    | '/portal/terms'
    | '/portal/verify'
    | '/portal/welcome'
    | '/portal'
    | '/customers/$customerId'
    | '/guests/$guestId'
    | '/locations/$locationId'
    | '/organizations/$orgId'
    | '/portals/$portalId'
    | '/routers/$routerId'
    | '/workspace/analytics'
    | '/workspace/audit'
    | '/workspace/billing'
    | '/workspace/company'
    | '/workspace/guests'
    | '/workspace/help'
    | '/workspace/locations'
    | '/workspace/notifications'
    | '/workspace/reports'
    | '/workspace/routers'
    | '/workspace/staff'
    | '/portal/auth/$method'
    | '/analytics'
    | '/api-keys'
    | '/audit'
    | '/billing'
    | '/branding'
    | '/customers'
    | '/exports'
    | '/feature-management'
    | '/guests'
    | '/help'
    | '/integrations'
    | '/locations'
    | '/marketplace'
    | '/monitoring'
    | '/notifications'
    | '/onboarding'
    | '/organizations'
    | '/plans'
    | '/portals'
    | '/rbac'
    | '/routers'
    | '/settings'
    | '/subscription'
    | '/system'
    | '/workspace'
    | '/workspace/locations/$locationId'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/forgot-password'
    | '/login'
    | '/portal'
    | '/reset-password'
    | '/session-expired'
    | '/verify-otp'
    | '/_authenticated/dashboard'
    | '/_authenticated/workspace'
    | '/portal/ad'
    | '/portal/auth'
    | '/portal/expired'
    | '/portal/failure'
    | '/portal/offline'
    | '/portal/redirect'
    | '/portal/session'
    | '/portal/success'
    | '/portal/terms'
    | '/portal/verify'
    | '/portal/welcome'
    | '/portal/'
    | '/_authenticated/customers/$customerId'
    | '/_authenticated/guests/$guestId'
    | '/_authenticated/locations/$locationId'
    | '/_authenticated/organizations/$orgId'
    | '/_authenticated/portals/$portalId'
    | '/_authenticated/routers/$routerId'
    | '/_authenticated/workspace/analytics'
    | '/_authenticated/workspace/audit'
    | '/_authenticated/workspace/billing'
    | '/_authenticated/workspace/company'
    | '/_authenticated/workspace/guests'
    | '/_authenticated/workspace/help'
    | '/_authenticated/workspace/locations'
    | '/_authenticated/workspace/notifications'
    | '/_authenticated/workspace/reports'
    | '/_authenticated/workspace/routers'
    | '/_authenticated/workspace/staff'
    | '/portal/auth/$method'
    | '/_authenticated/analytics/'
    | '/_authenticated/api-keys/'
    | '/_authenticated/audit/'
    | '/_authenticated/billing/'
    | '/_authenticated/branding/'
    | '/_authenticated/customers/'
    | '/_authenticated/exports/'
    | '/_authenticated/feature-management/'
    | '/_authenticated/guests/'
    | '/_authenticated/help/'
    | '/_authenticated/integrations/'
    | '/_authenticated/locations/'
    | '/_authenticated/marketplace/'
    | '/_authenticated/monitoring/'
    | '/_authenticated/notifications/'
    | '/_authenticated/onboarding/'
    | '/_authenticated/organizations/'
    | '/_authenticated/plans/'
    | '/_authenticated/portals/'
    | '/_authenticated/rbac/'
    | '/_authenticated/routers/'
    | '/_authenticated/settings/'
    | '/_authenticated/subscription/'
    | '/_authenticated/system/'
    | '/_authenticated/workspace/'
    | '/_authenticated/workspace/locations/$locationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  PortalRoute: typeof PortalRouteWithChildren
  ResetPasswordRoute: typeof ResetPasswordRoute
  SessionExpiredRoute: typeof SessionExpiredRoute
  VerifyOtpRoute: typeof VerifyOtpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify-otp': {
      id: '/verify-otp'
      path: '/verify-otp'
      fullPath: '/verify-otp'
      preLoaderRoute: typeof VerifyOtpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/session-expired': {
      id: '/session-expired'
      path: '/session-expired'
      fullPath: '/session-expired'
      preLoaderRoute: typeof SessionExpiredRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal': {
      id: '/portal'
      path: '/portal'
      fullPath: '/portal'
      preLoaderRoute: typeof PortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/': {
      id: '/portal/'
      path: '/'
      fullPath: '/portal/'
      preLoaderRoute: typeof PortalIndexRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/welcome': {
      id: '/portal/welcome'
      path: '/welcome'
      fullPath: '/portal/welcome'
      preLoaderRoute: typeof PortalWelcomeRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/verify': {
      id: '/portal/verify'
      path: '/verify'
      fullPath: '/portal/verify'
      preLoaderRoute: typeof PortalVerifyRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/terms': {
      id: '/portal/terms'
      path: '/terms'
      fullPath: '/portal/terms'
      preLoaderRoute: typeof PortalTermsRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/success': {
      id: '/portal/success'
      path: '/success'
      fullPath: '/portal/success'
      preLoaderRoute: typeof PortalSuccessRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/session': {
      id: '/portal/session'
      path: '/session'
      fullPath: '/portal/session'
      preLoaderRoute: typeof PortalSessionRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/redirect': {
      id: '/portal/redirect'
      path: '/redirect'
      fullPath: '/portal/redirect'
      preLoaderRoute: typeof PortalRedirectRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/offline': {
      id: '/portal/offline'
      path: '/offline'
      fullPath: '/portal/offline'
      preLoaderRoute: typeof PortalOfflineRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/failure': {
      id: '/portal/failure'
      path: '/failure'
      fullPath: '/portal/failure'
      preLoaderRoute: typeof PortalFailureRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/expired': {
      id: '/portal/expired'
      path: '/expired'
      fullPath: '/portal/expired'
      preLoaderRoute: typeof PortalExpiredRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/auth': {
      id: '/portal/auth'
      path: '/auth'
      fullPath: '/portal/auth'
      preLoaderRoute: typeof PortalAuthRouteImport
      parentRoute: typeof PortalRoute
    }
    '/portal/ad': {
      id: '/portal/ad'
      path: '/ad'
      fullPath: '/portal/ad'
      preLoaderRoute: typeof PortalAdRouteImport
      parentRoute: typeof PortalRoute
    }
    '/_authenticated/workspace': {
      id: '/_authenticated/workspace'
      path: '/workspace'
      fullPath: '/workspace'
      preLoaderRoute: typeof AuthenticatedWorkspaceRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/': {
      id: '/_authenticated/workspace/'
      path: '/'
      fullPath: '/workspace/'
      preLoaderRoute: typeof AuthenticatedWorkspaceIndexRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/system/': {
      id: '/_authenticated/system/'
      path: '/system'
      fullPath: '/system/'
      preLoaderRoute: typeof AuthenticatedSystemIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/subscription/': {
      id: '/_authenticated/subscription/'
      path: '/subscription'
      fullPath: '/subscription/'
      preLoaderRoute: typeof AuthenticatedSubscriptionIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/settings/': {
      id: '/_authenticated/settings/'
      path: '/settings'
      fullPath: '/settings/'
      preLoaderRoute: typeof AuthenticatedSettingsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/routers/': {
      id: '/_authenticated/routers/'
      path: '/routers'
      fullPath: '/routers/'
      preLoaderRoute: typeof AuthenticatedRoutersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/rbac/': {
      id: '/_authenticated/rbac/'
      path: '/rbac'
      fullPath: '/rbac/'
      preLoaderRoute: typeof AuthenticatedRbacIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portals/': {
      id: '/_authenticated/portals/'
      path: '/portals'
      fullPath: '/portals/'
      preLoaderRoute: typeof AuthenticatedPortalsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/plans/': {
      id: '/_authenticated/plans/'
      path: '/plans'
      fullPath: '/plans/'
      preLoaderRoute: typeof AuthenticatedPlansIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/': {
      id: '/_authenticated/organizations/'
      path: '/organizations'
      fullPath: '/organizations/'
      preLoaderRoute: typeof AuthenticatedOrganizationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/onboarding/': {
      id: '/_authenticated/onboarding/'
      path: '/onboarding'
      fullPath: '/onboarding/'
      preLoaderRoute: typeof AuthenticatedOnboardingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/notifications/': {
      id: '/_authenticated/notifications/'
      path: '/notifications'
      fullPath: '/notifications/'
      preLoaderRoute: typeof AuthenticatedNotificationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/monitoring/': {
      id: '/_authenticated/monitoring/'
      path: '/monitoring'
      fullPath: '/monitoring/'
      preLoaderRoute: typeof AuthenticatedMonitoringIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/marketplace/': {
      id: '/_authenticated/marketplace/'
      path: '/marketplace'
      fullPath: '/marketplace/'
      preLoaderRoute: typeof AuthenticatedMarketplaceIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/': {
      id: '/_authenticated/locations/'
      path: '/locations'
      fullPath: '/locations/'
      preLoaderRoute: typeof AuthenticatedLocationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/integrations/': {
      id: '/_authenticated/integrations/'
      path: '/integrations'
      fullPath: '/integrations/'
      preLoaderRoute: typeof AuthenticatedIntegrationsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/help/': {
      id: '/_authenticated/help/'
      path: '/help'
      fullPath: '/help/'
      preLoaderRoute: typeof AuthenticatedHelpIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests/': {
      id: '/_authenticated/guests/'
      path: '/guests'
      fullPath: '/guests/'
      preLoaderRoute: typeof AuthenticatedGuestsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/feature-management/': {
      id: '/_authenticated/feature-management/'
      path: '/feature-management'
      fullPath: '/feature-management/'
      preLoaderRoute: typeof AuthenticatedFeatureManagementIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/exports/': {
      id: '/_authenticated/exports/'
      path: '/exports'
      fullPath: '/exports/'
      preLoaderRoute: typeof AuthenticatedExportsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/': {
      id: '/_authenticated/customers/'
      path: '/customers'
      fullPath: '/customers/'
      preLoaderRoute: typeof AuthenticatedCustomersIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/branding/': {
      id: '/_authenticated/branding/'
      path: '/branding'
      fullPath: '/branding/'
      preLoaderRoute: typeof AuthenticatedBrandingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/billing/': {
      id: '/_authenticated/billing/'
      path: '/billing'
      fullPath: '/billing/'
      preLoaderRoute: typeof AuthenticatedBillingIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/audit/': {
      id: '/_authenticated/audit/'
      path: '/audit'
      fullPath: '/audit/'
      preLoaderRoute: typeof AuthenticatedAuditIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/api-keys/': {
      id: '/_authenticated/api-keys/'
      path: '/api-keys'
      fullPath: '/api-keys/'
      preLoaderRoute: typeof AuthenticatedApiKeysIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/analytics/': {
      id: '/_authenticated/analytics/'
      path: '/analytics'
      fullPath: '/analytics/'
      preLoaderRoute: typeof AuthenticatedAnalyticsIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/portal/auth/$method': {
      id: '/portal/auth/$method'
      path: '/$method'
      fullPath: '/portal/auth/$method'
      preLoaderRoute: typeof PortalAuthMethodRouteImport
      parentRoute: typeof PortalAuthRoute
    }
    '/_authenticated/workspace/staff': {
      id: '/_authenticated/workspace/staff'
      path: '/staff'
      fullPath: '/workspace/staff'
      preLoaderRoute: typeof AuthenticatedWorkspaceStaffRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/routers': {
      id: '/_authenticated/workspace/routers'
      path: '/routers'
      fullPath: '/workspace/routers'
      preLoaderRoute: typeof AuthenticatedWorkspaceRoutersRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/reports': {
      id: '/_authenticated/workspace/reports'
      path: '/reports'
      fullPath: '/workspace/reports'
      preLoaderRoute: typeof AuthenticatedWorkspaceReportsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/notifications': {
      id: '/_authenticated/workspace/notifications'
      path: '/notifications'
      fullPath: '/workspace/notifications'
      preLoaderRoute: typeof AuthenticatedWorkspaceNotificationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/locations': {
      id: '/_authenticated/workspace/locations'
      path: '/locations'
      fullPath: '/workspace/locations'
      preLoaderRoute: typeof AuthenticatedWorkspaceLocationsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/help': {
      id: '/_authenticated/workspace/help'
      path: '/help'
      fullPath: '/workspace/help'
      preLoaderRoute: typeof AuthenticatedWorkspaceHelpRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/guests': {
      id: '/_authenticated/workspace/guests'
      path: '/guests'
      fullPath: '/workspace/guests'
      preLoaderRoute: typeof AuthenticatedWorkspaceGuestsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/company': {
      id: '/_authenticated/workspace/company'
      path: '/company'
      fullPath: '/workspace/company'
      preLoaderRoute: typeof AuthenticatedWorkspaceCompanyRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/billing': {
      id: '/_authenticated/workspace/billing'
      path: '/billing'
      fullPath: '/workspace/billing'
      preLoaderRoute: typeof AuthenticatedWorkspaceBillingRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/audit': {
      id: '/_authenticated/workspace/audit'
      path: '/audit'
      fullPath: '/workspace/audit'
      preLoaderRoute: typeof AuthenticatedWorkspaceAuditRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/workspace/analytics': {
      id: '/_authenticated/workspace/analytics'
      path: '/analytics'
      fullPath: '/workspace/analytics'
      preLoaderRoute: typeof AuthenticatedWorkspaceAnalyticsRouteImport
      parentRoute: typeof AuthenticatedWorkspaceRoute
    }
    '/_authenticated/routers/$routerId': {
      id: '/_authenticated/routers/$routerId'
      path: '/routers/$routerId'
      fullPath: '/routers/$routerId'
      preLoaderRoute: typeof AuthenticatedRoutersRouterIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/portals/$portalId': {
      id: '/_authenticated/portals/$portalId'
      path: '/portals/$portalId'
      fullPath: '/portals/$portalId'
      preLoaderRoute: typeof AuthenticatedPortalsPortalIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/organizations/$orgId': {
      id: '/_authenticated/organizations/$orgId'
      path: '/organizations/$orgId'
      fullPath: '/organizations/$orgId'
      preLoaderRoute: typeof AuthenticatedOrganizationsOrgIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/locations/$locationId': {
      id: '/_authenticated/locations/$locationId'
      path: '/locations/$locationId'
      fullPath: '/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/guests/$guestId': {
      id: '/_authenticated/guests/$guestId'
      path: '/guests/$guestId'
      fullPath: '/guests/$guestId'
      preLoaderRoute: typeof AuthenticatedGuestsGuestIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/customers/$customerId': {
      id: '/_authenticated/customers/$customerId'
      path: '/customers/$customerId'
      fullPath: '/customers/$customerId'
      preLoaderRoute: typeof AuthenticatedCustomersCustomerIdRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspace/locations/$locationId': {
      id: '/_authenticated/workspace/locations/$locationId'
      path: '/$locationId'
      fullPath: '/workspace/locations/$locationId'
      preLoaderRoute: typeof AuthenticatedWorkspaceLocationsLocationIdRouteImport
      parentRoute: typeof AuthenticatedWorkspaceLocationsRoute
    }
  }
}

interface AuthenticatedWorkspaceLocationsRouteChildren {
  AuthenticatedWorkspaceLocationsLocationIdRoute: typeof AuthenticatedWorkspaceLocationsLocationIdRoute
}

const AuthenticatedWorkspaceLocationsRouteChildren: AuthenticatedWorkspaceLocationsRouteChildren =
  {
    AuthenticatedWorkspaceLocationsLocationIdRoute:
      AuthenticatedWorkspaceLocationsLocationIdRoute,
  }

const AuthenticatedWorkspaceLocationsRouteWithChildren =
  AuthenticatedWorkspaceLocationsRoute._addFileChildren(
    AuthenticatedWorkspaceLocationsRouteChildren,
  )

interface AuthenticatedWorkspaceRouteChildren {
  AuthenticatedWorkspaceAnalyticsRoute: typeof AuthenticatedWorkspaceAnalyticsRoute
  AuthenticatedWorkspaceAuditRoute: typeof AuthenticatedWorkspaceAuditRoute
  AuthenticatedWorkspaceBillingRoute: typeof AuthenticatedWorkspaceBillingRoute
  AuthenticatedWorkspaceCompanyRoute: typeof AuthenticatedWorkspaceCompanyRoute
  AuthenticatedWorkspaceGuestsRoute: typeof AuthenticatedWorkspaceGuestsRoute
  AuthenticatedWorkspaceHelpRoute: typeof AuthenticatedWorkspaceHelpRoute
  AuthenticatedWorkspaceLocationsRoute: typeof AuthenticatedWorkspaceLocationsRouteWithChildren
  AuthenticatedWorkspaceNotificationsRoute: typeof AuthenticatedWorkspaceNotificationsRoute
  AuthenticatedWorkspaceReportsRoute: typeof AuthenticatedWorkspaceReportsRoute
  AuthenticatedWorkspaceRoutersRoute: typeof AuthenticatedWorkspaceRoutersRoute
  AuthenticatedWorkspaceStaffRoute: typeof AuthenticatedWorkspaceStaffRoute
  AuthenticatedWorkspaceIndexRoute: typeof AuthenticatedWorkspaceIndexRoute
}

const AuthenticatedWorkspaceRouteChildren: AuthenticatedWorkspaceRouteChildren =
  {
    AuthenticatedWorkspaceAnalyticsRoute: AuthenticatedWorkspaceAnalyticsRoute,
    AuthenticatedWorkspaceAuditRoute: AuthenticatedWorkspaceAuditRoute,
    AuthenticatedWorkspaceBillingRoute: AuthenticatedWorkspaceBillingRoute,
    AuthenticatedWorkspaceCompanyRoute: AuthenticatedWorkspaceCompanyRoute,
    AuthenticatedWorkspaceGuestsRoute: AuthenticatedWorkspaceGuestsRoute,
    AuthenticatedWorkspaceHelpRoute: AuthenticatedWorkspaceHelpRoute,
    AuthenticatedWorkspaceLocationsRoute:
      AuthenticatedWorkspaceLocationsRouteWithChildren,
    AuthenticatedWorkspaceNotificationsRoute:
      AuthenticatedWorkspaceNotificationsRoute,
    AuthenticatedWorkspaceReportsRoute: AuthenticatedWorkspaceReportsRoute,
    AuthenticatedWorkspaceRoutersRoute: AuthenticatedWorkspaceRoutersRoute,
    AuthenticatedWorkspaceStaffRoute: AuthenticatedWorkspaceStaffRoute,
    AuthenticatedWorkspaceIndexRoute: AuthenticatedWorkspaceIndexRoute,
  }

const AuthenticatedWorkspaceRouteWithChildren =
  AuthenticatedWorkspaceRoute._addFileChildren(
    AuthenticatedWorkspaceRouteChildren,
  )

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedWorkspaceRoute: typeof AuthenticatedWorkspaceRouteWithChildren
  AuthenticatedCustomersCustomerIdRoute: typeof AuthenticatedCustomersCustomerIdRoute
  AuthenticatedGuestsGuestIdRoute: typeof AuthenticatedGuestsGuestIdRoute
  AuthenticatedLocationsLocationIdRoute: typeof AuthenticatedLocationsLocationIdRoute
  AuthenticatedOrganizationsOrgIdRoute: typeof AuthenticatedOrganizationsOrgIdRoute
  AuthenticatedPortalsPortalIdRoute: typeof AuthenticatedPortalsPortalIdRoute
  AuthenticatedRoutersRouterIdRoute: typeof AuthenticatedRoutersRouterIdRoute
  AuthenticatedAnalyticsIndexRoute: typeof AuthenticatedAnalyticsIndexRoute
  AuthenticatedApiKeysIndexRoute: typeof AuthenticatedApiKeysIndexRoute
  AuthenticatedAuditIndexRoute: typeof AuthenticatedAuditIndexRoute
  AuthenticatedBillingIndexRoute: typeof AuthenticatedBillingIndexRoute
  AuthenticatedBrandingIndexRoute: typeof AuthenticatedBrandingIndexRoute
  AuthenticatedCustomersIndexRoute: typeof AuthenticatedCustomersIndexRoute
  AuthenticatedExportsIndexRoute: typeof AuthenticatedExportsIndexRoute
  AuthenticatedFeatureManagementIndexRoute: typeof AuthenticatedFeatureManagementIndexRoute
  AuthenticatedGuestsIndexRoute: typeof AuthenticatedGuestsIndexRoute
  AuthenticatedHelpIndexRoute: typeof AuthenticatedHelpIndexRoute
  AuthenticatedIntegrationsIndexRoute: typeof AuthenticatedIntegrationsIndexRoute
  AuthenticatedLocationsIndexRoute: typeof AuthenticatedLocationsIndexRoute
  AuthenticatedMarketplaceIndexRoute: typeof AuthenticatedMarketplaceIndexRoute
  AuthenticatedMonitoringIndexRoute: typeof AuthenticatedMonitoringIndexRoute
  AuthenticatedNotificationsIndexRoute: typeof AuthenticatedNotificationsIndexRoute
  AuthenticatedOnboardingIndexRoute: typeof AuthenticatedOnboardingIndexRoute
  AuthenticatedOrganizationsIndexRoute: typeof AuthenticatedOrganizationsIndexRoute
  AuthenticatedPlansIndexRoute: typeof AuthenticatedPlansIndexRoute
  AuthenticatedPortalsIndexRoute: typeof AuthenticatedPortalsIndexRoute
  AuthenticatedRbacIndexRoute: typeof AuthenticatedRbacIndexRoute
  AuthenticatedRoutersIndexRoute: typeof AuthenticatedRoutersIndexRoute
  AuthenticatedSettingsIndexRoute: typeof AuthenticatedSettingsIndexRoute
  AuthenticatedSubscriptionIndexRoute: typeof AuthenticatedSubscriptionIndexRoute
  AuthenticatedSystemIndexRoute: typeof AuthenticatedSystemIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedWorkspaceRoute: AuthenticatedWorkspaceRouteWithChildren,
  AuthenticatedCustomersCustomerIdRoute: AuthenticatedCustomersCustomerIdRoute,
  AuthenticatedGuestsGuestIdRoute: AuthenticatedGuestsGuestIdRoute,
  AuthenticatedLocationsLocationIdRoute: AuthenticatedLocationsLocationIdRoute,
  AuthenticatedOrganizationsOrgIdRoute: AuthenticatedOrganizationsOrgIdRoute,
  AuthenticatedPortalsPortalIdRoute: AuthenticatedPortalsPortalIdRoute,
  AuthenticatedRoutersRouterIdRoute: AuthenticatedRoutersRouterIdRoute,
  AuthenticatedAnalyticsIndexRoute: AuthenticatedAnalyticsIndexRoute,
  AuthenticatedApiKeysIndexRoute: AuthenticatedApiKeysIndexRoute,
  AuthenticatedAuditIndexRoute: AuthenticatedAuditIndexRoute,
  AuthenticatedBillingIndexRoute: AuthenticatedBillingIndexRoute,
  AuthenticatedBrandingIndexRoute: AuthenticatedBrandingIndexRoute,
  AuthenticatedCustomersIndexRoute: AuthenticatedCustomersIndexRoute,
  AuthenticatedExportsIndexRoute: AuthenticatedExportsIndexRoute,
  AuthenticatedFeatureManagementIndexRoute:
    AuthenticatedFeatureManagementIndexRoute,
  AuthenticatedGuestsIndexRoute: AuthenticatedGuestsIndexRoute,
  AuthenticatedHelpIndexRoute: AuthenticatedHelpIndexRoute,
  AuthenticatedIntegrationsIndexRoute: AuthenticatedIntegrationsIndexRoute,
  AuthenticatedLocationsIndexRoute: AuthenticatedLocationsIndexRoute,
  AuthenticatedMarketplaceIndexRoute: AuthenticatedMarketplaceIndexRoute,
  AuthenticatedMonitoringIndexRoute: AuthenticatedMonitoringIndexRoute,
  AuthenticatedNotificationsIndexRoute: AuthenticatedNotificationsIndexRoute,
  AuthenticatedOnboardingIndexRoute: AuthenticatedOnboardingIndexRoute,
  AuthenticatedOrganizationsIndexRoute: AuthenticatedOrganizationsIndexRoute,
  AuthenticatedPlansIndexRoute: AuthenticatedPlansIndexRoute,
  AuthenticatedPortalsIndexRoute: AuthenticatedPortalsIndexRoute,
  AuthenticatedRbacIndexRoute: AuthenticatedRbacIndexRoute,
  AuthenticatedRoutersIndexRoute: AuthenticatedRoutersIndexRoute,
  AuthenticatedSettingsIndexRoute: AuthenticatedSettingsIndexRoute,
  AuthenticatedSubscriptionIndexRoute: AuthenticatedSubscriptionIndexRoute,
  AuthenticatedSystemIndexRoute: AuthenticatedSystemIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

interface PortalAuthRouteChildren {
  PortalAuthMethodRoute: typeof PortalAuthMethodRoute
}

const PortalAuthRouteChildren: PortalAuthRouteChildren = {
  PortalAuthMethodRoute: PortalAuthMethodRoute,
}

const PortalAuthRouteWithChildren = PortalAuthRoute._addFileChildren(
  PortalAuthRouteChildren,
)

interface PortalRouteChildren {
  PortalAdRoute: typeof PortalAdRoute
  PortalAuthRoute: typeof PortalAuthRouteWithChildren
  PortalExpiredRoute: typeof PortalExpiredRoute
  PortalFailureRoute: typeof PortalFailureRoute
  PortalOfflineRoute: typeof PortalOfflineRoute
  PortalRedirectRoute: typeof PortalRedirectRoute
  PortalSessionRoute: typeof PortalSessionRoute
  PortalSuccessRoute: typeof PortalSuccessRoute
  PortalTermsRoute: typeof PortalTermsRoute
  PortalVerifyRoute: typeof PortalVerifyRoute
  PortalWelcomeRoute: typeof PortalWelcomeRoute
  PortalIndexRoute: typeof PortalIndexRoute
}

const PortalRouteChildren: PortalRouteChildren = {
  PortalAdRoute: PortalAdRoute,
  PortalAuthRoute: PortalAuthRouteWithChildren,
  PortalExpiredRoute: PortalExpiredRoute,
  PortalFailureRoute: PortalFailureRoute,
  PortalOfflineRoute: PortalOfflineRoute,
  PortalRedirectRoute: PortalRedirectRoute,
  PortalSessionRoute: PortalSessionRoute,
  PortalSuccessRoute: PortalSuccessRoute,
  PortalTermsRoute: PortalTermsRoute,
  PortalVerifyRoute: PortalVerifyRoute,
  PortalWelcomeRoute: PortalWelcomeRoute,
  PortalIndexRoute: PortalIndexRoute,
}

const PortalRouteWithChildren =
  PortalRoute._addFileChildren(PortalRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  PortalRoute: PortalRouteWithChildren,
  ResetPasswordRoute: ResetPasswordRoute,
  SessionExpiredRoute: SessionExpiredRoute,
  VerifyOtpRoute: VerifyOtpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
